import os,glob,platform

Import('baseEnv')
Import('listFiles')
progEnv = baseEnv.Clone()
libEnv = baseEnv.Clone()

libEnv.Tool('pyIrfLoaderLib', depsOnly = 1)
pyIrfLoaderStaticLib = libEnv.StaticLibrary('_pyIrfLoader', 'src/pyIrfLoader.i')
pyIrfLoaderSharedLib = libEnv.SharedLibrary('_pyIrfLoader', 'src/pyIrfLoader.i')

progEnv.Tool('registerObjects', package = 'pyIrfLoader', libraries = [pyIrfLoaderStaticLib, pyIrfLoaderSharedLib], includes = listFiles(['pyIrfLoader/*.h']))