# -*- python -*-
# $Header$
# Authors: James Chiang <jchiang@slac.stanford.edu>
# Version: pyIrfLoader-00-01-04
import os,glob,platform

Import('baseEnv')
Import('listFiles')
progEnv = baseEnv.Clone()
libEnv = baseEnv.Clone()

libEnv.Tool('pyIrfLoaderLib', depsOnly = 1)
pyIrfLoaderLib = libEnv.SwigLibrary('_pyIrfLoader', 'src/pyIrfLoader.i')

progEnv.Tool('registerTargets',
             package   = 'pyIrfLoader',
             swigLibraryCxts = [[pyIrfLoaderLib, libEnv]],
             includes  = listFiles(['pyIrfLoader/*.h']),
             python    = ['src/pyIrfLoader.py'])
