import os,glob,platform

Import('baseEnv')
Import('listFiles')
progEnv = baseEnv.Clone()
libEnv = baseEnv.Clone()

pyIrfLoaderStaticLib = libEnv.StaticLibrary('lib_pyIrfLoader', 'src/pyIrfLoader.i')
pyIrfLoaderSharedLib = libEnv.SharedLibrary('lib_pyIrfLoader', 'src/pyIrfLoader.i')

progEnv.Tool('registerObjects', package = 'pyIrfLoader', libraries = [pyIrfLoaderStaticLib, pyIrfLoaderSharedLib], includes = listFiles(['pyIrfLoader/*.h']))