# -*- python -*-
# $Id$
# Authors: James Chiang <jchiang@slac.stanford.edu>
# Version: caldb-07-00-03
Import('baseEnv')
Import('listFiles')

baseEnv.Tool('registerTargets', package='caldb',
             data=listFiles(['CALDB/*'], recursive=True))
