# -*- python -*-
# $Id$
# Authors: James Chiang <jchiang@slac.stanford.edu>
# Version: caldb-03-03-00
Import('baseEnv')
Import('listFiles')

baseEnv.Tool('registerTargets', package = 'caldb', data = listFiles(['CALDB/*'], recursive = True))
