# -*- python -*-
# $Id$
# Authors: James Chiang <jchiang@slac.stanford.edu>
# Version: caldb_release-05-00-00

Import('baseEnv')
Import('listFiles')

baseEnv.Tool('registerTargets',
             package = 'caldb_response')
                              
