# -*- python -*-
# $Id$
# Authors: James Chiang <jchiang@slac.stanford.edu>
# Version: rootIrfLoader-01-00-02
Import('baseEnv')
Import('listFiles')
progEnv = baseEnv.Clone()
libEnv = baseEnv.Clone()

cintSources = listFiles(['src/rootIrfLoader/*.h'])
extraSources = listFiles(['src/rootIrfLoader/*.cxx'])

libEnv.Tool('rootIrfLoaderLib', depsOnly = 1)

rootIrfLoaderCint = libEnv.Rootcint('rootIrfLoader/rootIrfLoader_rootcint.cxx',
                                    cintSources, includes = ['.', 'src' ])
                                    
libEnv['rootcint_node'] = rootIrfLoaderCint

rootIrfLoaderLib = libEnv.SharedLibrary('rootIrfLoader', 
                                        listFiles(['src/*.cxx']) + extraSources)

progEnv.Tool('registerTargets', package = 'rootIrfLoader',
             rootcintSharedCxts = [[rootIrfLoaderLib, libEnv]],
             includes=cintSources)
