# -*- python -*-
# $Id$
# Authors: James Chiang <jchiang@slac.stanford.edu>
# Version: testResponse-02-00-04
Import('baseEnv')
Import('listFiles')
progEnv = baseEnv.Clone()
libEnv = baseEnv.Clone()

if baseEnv['PLATFORM'] == "win32":
    libEnv.Tool('testResponseLib', depsOnly = 1)

testResponseLib = libEnv.SharedLibrary('testResponse', listFiles(['src/*.cxx']))

progEnv.Tool('testResponseLib')
progEnv.Tool('addLibrary', library = progEnv['cppunitLibs'])
test_testResponseBin = progEnv.Program('test_testResponse', listFiles(['src/test/*.cxx']))

progEnv.Tool('registerTargets', package = 'testResponse',
             libraryCxts = [[testResponseLib, libEnv]],
             testAppCxts = [[test_testResponseBin, progEnv]],
             includes = listFiles(['testResponse/*.h']))
