#$Id$
Import('baseEnv')
Import('listFiles')
progEnv = baseEnv.Clone()
libEnv = baseEnv.Clone()

if baseEnv['PLATFORM'] != "win32":
        progEnv.AppendUnique(CPPDEFINES = ['TRAP_FPE'])

libEnv.Tool('testResponseLib', depsOnly = 1)
testResponseLib = libEnv.StaticLibrary('testResponse', listFiles(['src/*.cxx']))

progEnv.Tool('testResponseLib')
progEnv.Tool('addLibrary', library = progEnv['cppunitLibs'])
test_testResponseBin = progEnv.Program('test_testResponse', listFiles(['src/test/*.cxx']))

progEnv.Tool('registerObjects', package = 'testResponse', libraries = [testResponseLib], testApps = [test_testResponseBin], includes = listFiles(['testResponse/*.h']))
