# -*- python -*-
# $Id$
# Authors: James Chiang <jchiang@slac.stanford.edu>
# Version: g25Response-02-00-03

Import('baseEnv')
Import('listFiles')
progEnv = baseEnv.Clone()
libEnv = baseEnv.Clone()

libEnv.Tool('g25ResponseLib', depsOnly = 1)
g25ResponseLib = libEnv.StaticLibrary('g25Response', listFiles(['src/*.cxx']))

progEnv.Tool('g25ResponseLib')
test_g25ResponseBin = progEnv.Program('test_g25Response', listFiles(['src/test/*.cxx']))

progEnv.Tool('registerTargets', package = 'g25Response',
             staticLibraryCxts = [[g25ResponseLib, libEnv]],
             testAppCxts = [[test_g25ResponseBin, progEnv]],
             includes = listFiles(['g25Response/*.h']))
