#$Id$
Import('baseEnv')
Import('listFiles')
progEnv = baseEnv.Clone()
libEnv = baseEnv.Clone()

if baseEnv['PLATFORM'] != "win32":
        progEnv.AppendUnique(CPPDEFINES = ['TRAP_FPE'])

libEnv.Tool('g25ResponseLib', depsOnly = 1)
g25ResponseLib = libEnv.StaticLibrary('g25Response', listFiles(['src/*.cxx']))

progEnv.Tool('g25ResponseLib')
test_g25ResponseBin = progEnv.Program('test_g25Response', listFiles(['src/test/*.cxx']))

progEnv.Tool('registerObjects', package = 'g25Response', libraries = [g25ResponseLib], testApps = [test_g25ResponseBin], includes = listFiles(['g25Response/*.h']))