# -*- python -*-
# $Id$
# Authors: J. Chiang <jchiang@slac.stanford.edu>
# Version: latResponse-02-01-04
Import('baseEnv')
Import('listFiles')
libEnv = baseEnv.Clone()
progEnv = baseEnv.Clone()

libEnv.Tool('latResponseLib', depsOnly = 1)
latResponseLib = libEnv.StaticLibrary('latResponse', listFiles(['src/*.cxx']))

progEnv.Tool('latResponseLib')
progEnv.Tool('addLibrary', library = baseEnv['cppunitLibs'])
test_latResponse = progEnv.Program('test_latResponse', listFiles(['src/test/*.cxx']))

progEnv.Tool('registerObjects', package = 'latResponse', libraries = [latResponseLib], testApps = [test_latResponse], includes = listFiles(['latResponse/*.h']),
             data = listFiles(['data/*'], recursive = True))
