# -*- python -*-
#
# $Header$
#
# Authors: James Chiang <jchiang@slac.stanford.edu>
# Version: irfInterface-03-00-03
Import('baseEnv')
Import('listFiles')
progEnv = baseEnv.Clone()
libEnv = baseEnv.Clone()

libEnv.Tool('addLinkDeps', package='irfInterface', toBuild='shared')

irfInterfaceLib = libEnv.SharedLibrary('irfInterface', listFiles(['src/*.cxx']))

progEnv.Tool('irfInterfaceLib')
progEnv.Tool('addLibrary', library=progEnv['cppunitLibs'])

if baseEnv['PLATFORM'] == 'posix':
    progEnv.Append(CPPDEFINES='TRAP_FPE')

test_irfInterfaceBin = progEnv.Program('test_irfInterface',
                                       listFiles(['src/test/*.cxx']))

progEnv.Tool('registerTargets', package='irfInterface', 
             libraryCxts=[[irfInterfaceLib, libEnv]], 
             testAppCxts=[[test_irfInterfaceBin, progEnv]], 
             includes=listFiles(['irfInterface/*.h']),
             data=['data/P6_V3_DIFFUSE_eff.txt'])
