# -*- python -*-
#
# $Header$
#

import glob, os, platform

Import('baseEnv')
Import('listFiles')
progEnv = baseEnv.Clone()
libEnv = baseEnv.Clone()

if platform.system() == 'Linux':
    progEnv.Append(CPPDEFINES='TRAP_FPE')

irfInterfaceLib = libEnv.StaticLibrary('irfInterface', listFiles(['src/*.cxx']))

progEnv.Tool('irfInterfaceLib')
progEnv.Tool('addLibrary', library=progEnv['cppunitLibs'])

test_irfInterfaceBin = progEnv.Program('test_irfInterface',
                                       listFiles(['src/test/*.cxx']))

progEnv.Tool('registerObjects', package='irfInterface', 
             libraries=[irfInterfaceLib], 
             testApps=[test_irfInterfaceBin], 
             includes=listFiles(['irfInterface/*.h']))
