# -*- python -*-
#
# $Header$
#
# Authors: James Chiang <jchiang@slac.stanford.edu>
# Version: irfInterface-02-02-01
Import('baseEnv')
Import('listFiles')
progEnv = baseEnv.Clone()
libEnv = baseEnv.Clone()

libEnv.Tool('irfInterfaceLib', depsOnly = 1)
irfInterfaceLib = libEnv.StaticLibrary('irfInterface', listFiles(['src/*.cxx']))

progEnv.Tool('irfInterfaceLib')
progEnv.Tool('addLibrary', library=progEnv['cppunitLibs'])

test_irfInterfaceBin = progEnv.Program('test_irfInterface',
                                       listFiles(['src/test/*.cxx']))

progEnv.Tool('registerObjects', package='irfInterface', 
             libraries=[irfInterfaceLib], 
             testApps=[test_irfInterfaceBin], 
             includes=listFiles(['irfInterface/*.h']))
