/** Doxygen mainpage

  @mainpage package irfs/testResponse

  @section intro Introduction

  This implementation is intended to provide a well-behaved set of
  response functions for testing the Science Tools and source
  detection algorithms.  Although they are based on data from Gleam
  simulations, they are not intended for analysis of simulated
  astrophysical observations generated by Gleam, nor should they be
  considered in any way as being representative of the performance of
  the LAT.

  These response functions are based on the 4.945 M events generated
  using GlastRelease v4r2.
  
  @section psf Point Spread Function

  Because of multiple scattering, the angular size of the deviations
  of the reconstructed photon directions from the true directions is
  expected to scale approximately as \f$E^{-1}\f$.  One also expects
  there to be a dependence of this angular scale on where in the LAT
  the photon converts and on the photon incident direction with
  respect to the instrument axes.  Following conventions, we partition
  the data into "front"-converting (layers 0 to 11) and
  "back"-converting (layers 12 to 15) events; and we consider
  dependence on true photon energy and incident inclination with
  respect to the instrument z-axis, ignoring any azimuthal dependence.
  We also ignore any azimuthal asymmetry about the photon incident
  direction.

  For this analysis, we fit profile plots of <tt>BestDirErr</tt>
  versus log10(<tt>McEnergy</tt>).  <tt>BestDirErr</tt> is defined in
  terms of the merit variables using this bit of code from
  irfAnalysis/src/PSF.cxx:
  @verbatim
            if (IMvertexProb<0.5||VtxAngle==0.0){
                dir_err=McTkr1DirErr;
            }else{
                dir_err=McDirErr;
            }
  @endverbatim

  Here, <tt>dir_err</tt> is saved in a friend tree as
  <tt>BestDirErr</tt> and should logically be put into the merit tuple
  itself as part of the standard Gleam output.

  The parameterization we use for fitting these profile plots is
  \f[
  \tilde{\theta} \equiv \theta_0({\tt McZDir})
                         \left(\frac{1}{{\tt McEnergy}} 
                          + \frac{1}{E_b}\right)^\delta
  \f]
  where
  \f[
  \theta_0 \equiv p_0({\tt McZDir} + 1)^2 + p_1
  \f]
  For front-converting events, we find
  \f$(p_0, p_1, E_b, \delta) = (3.78, 1.81, 0.80, 5\times10^4)\f$, while
  for back-converting events, 
  \f$(p_0, p_1, E_b, \delta) = (6.80, 4.03, 0.85, 2.75\times10^4)\f$.

  Here are a sample of profile plots for various ranges of photon
  inclination:
  
  @image html bestDirErr_fits.png

  The above parameterization sets the scaling for the deviations of
  reconstructed from true direction.  For the psf distributions of the
  scaled deviations, \f$x \equiv \theta/\tilde{\theta}\f$, we use a
  form similar to one used by Toby Burnett (originally suggested by
  Jean Ballet) in a slightly different context:
  
  \f[
  \frac{dN}{dx} = p_0x\left[1 + \frac{2x}{\gamma-1}\right]^{-\gamma}
  \f]

  The form for the coefficient of \f$x\f$-term inside the brackets
  ensures that \f$dN/dx\$ peaks at \$x = 1\f$.
*/
