# -*- python -*-
# $Id$
# Authors: James Chiang <jchiang@slac.stanford.edu>
# Version: dc1Response-02-00-04
Import('baseEnv')
Import('listFiles')
progEnv = baseEnv.Clone()
libEnv = baseEnv.Clone()

if baseEnv['PLATFORM'] == "win32":
    libEnv.Tool('dc1ResponseLib', depsOnly = 1)
dc1ResponseLib = libEnv.SharedLibrary('dc1Response', listFiles(['src/*.cxx']))

progEnv.Tool('dc1ResponseLib')
test_dc1ResponseBin = progEnv.Program('test_dc1Response', listFiles(['src/test/*.cxx']))

progEnv.Tool('registerTargets', package = 'dc1Response',
             libraryCxts = [[dc1ResponseLib, libEnv]],
             testAppCxts = [[test_dc1ResponseBin, progEnv]],
             includes = listFiles(['dc1Response/*.h']))
