# -*- python -*-
# $Id$
# Authors: James Chiang <jchiang@slac.stanford.edu>
# Version: dc2Response-03-01-03
Import('baseEnv')
Import('listFiles')
progEnv = baseEnv.Clone()
libEnv = baseEnv.Clone()

libEnv.Tool('dc2ResponseLib', depsOnly = 1)
dc2ResponseLib = libEnv.StaticLibrary('dc2Response', listFiles(['src/*.cxx']))

progEnv.Tool('dc2ResponseLib')
test_dc2ResponseBin = progEnv.Program('test_dc2Response', listFiles(['src/test/*.cxx']))

progEnv.Tool('registerObjects', package = 'dc2Response', libraries = [dc2ResponseLib], testApps = [test_dc2ResponseBin], includes = listFiles(['dc2Response/*.h']))
