# -*- python -*-
# $Id$
# Authors: James Chiang <jchiang@slac.stanford.edu>
# Version: dc2Response-03-01-05
Import('baseEnv')
Import('listFiles')
progEnv = baseEnv.Clone()
libEnv = baseEnv.Clone()

libEnv.Tool('addLinkDeps', package='dc2Response', toBuild='shared')

dc2ResponseLib = libEnv.SharedLibrary('dc2Response', listFiles(['src/*.cxx']))

progEnv.Tool('dc2ResponseLib')

test_dc2ResponseBin = progEnv.Program('test_dc2Response', listFiles(['src/test/*.cxx']))

progEnv.Tool('registerTargets', package = 'dc2Response',
             libraryCxts = [[dc2ResponseLib, libEnv]],
             testAppCxts = [[test_dc2ResponseBin, progEnv]],
             includes = listFiles(['dc2Response/*.h']))
