
import glob,os,platform

Import('baseEnv')
Import('listFiles')
progEnv = baseEnv.Clone()
libEnv = baseEnv.Clone()

if platform.system() == 'Linux':
        progEnv.Append(CPPDEFINES = 'TRAP_FPE')

irfUtilLib = libEnv.StaticLibrary('irfUtil', listFiles(['src/*.cxx', 'src/*.c']))

progEnv.Tool('registerObjects', package = 'irfUtil', libraries = [irfUtilLib], includes = listFiles(['irfUtil/*.h']))