# -*- python -*-
# $Id$
# Authors: James Chiang <jchiang@slac.stanford.edu>
# Version: irfUtil-01-00-00
Import('baseEnv')
Import('listFiles')
progEnv = baseEnv.Clone()
libEnv = baseEnv.Clone()

irfUtilLib = libEnv.StaticLibrary('irfUtil',
                                  listFiles(['src/*.cxx', 'src/*.c']))

progEnv.Tool('irfUtilLib')

test_irfUtil = progEnv.Program('test_irfUtil', listFiles(['src/test/*.cxx']))

progEnv.Tool('registerTargets', package='irfUtil',
             staticLibraryCxts=[[irfUtilLib, libEnv]],
             testAppCxts=[[test_irfUtil, progEnv]],
             includes=listFiles(['irfUtil/*.h']), recursive=True)
