# -*- python -*-
# $Id$
# Authors: James Chiang <jchiang@slac.stanford.edu>
# Version: irfUtil-00-04-03
Import('baseEnv')
Import('listFiles')
progEnv = baseEnv.Clone()
libEnv = baseEnv.Clone()

libEnv.Tool('irfUtilLib', depsOnly = 1)
irfUtilLib = libEnv.StaticLibrary('irfUtil', listFiles(['src/*.cxx', 'src/*.c']))

progEnv.Tool('registerTargets', package = 'irfUtil', staticLibraryCxts = [[irfUtilLib, libEnv]],
             includes = listFiles(['irfUtil/*.h']))
