# -*- python -*-
# $Id$
# Authors: James Chiang <jchiang@slac.stanford.edu>
# Version: dc1aResponse-02-00-01

Import('baseEnv')
Import('listFiles')
progEnv = baseEnv.Clone()
libEnv = baseEnv.Clone()

libEnv.Tool('dc1aResponseLib', depsOnly = 1)
dc1aResponseLib = libEnv.StaticLibrary('dc1aResponse', listFiles(['src/*.cxx']))

progEnv.Tool('dc1aResponseLib')
test_dc1aResponseBin = progEnv.Program('test_dc1aResponse', listFiles(['src/test/*.cxx']))

progEnv.Tool('registerObjects', package = 'dc1aResponse', libraries = [dc1aResponseLib], testApps = [test_dc1aResponseBin], includes = listFiles(['dc1aResponse/*.h']))
