# -*- python -*-
# $Id$
# Authors: James Chiang <jchiang@slac.stanford.edu>
# Version: dc1aResponse-02-00-04

Import('baseEnv')
Import('listFiles')
progEnv = baseEnv.Clone()
libEnv = baseEnv.Clone()

libEnv.Tool('addLinkDeps', pacakge='dc1aResponse', toBuild='shared')

dc1aResponseLib = libEnv.SharedLibrary('dc1aResponse', listFiles(['src/*.cxx']))

progEnv.Tool('dc1aResponseLib')
test_dc1aResponseBin = progEnv.Program('test_dc1aResponse', listFiles(['src/test/*.cxx']))

progEnv.Tool('registerTargets', package = 'dc1aResponse',
             libraryCxts = [[dc1aResponseLib,libEnv]],
             testAppCxts = [[test_dc1aResponseBin, progEnv]],
             includes = listFiles(['dc1aResponse/*.h']))
