#$id
import platform

Import('baseEnv')
Import('listFiles')
progEnv = baseEnv.Clone()
libEnv = baseEnv.Clone()

if baseEnv['PLATFORM'] != 'win32':
        progEnv.Append(CPPDEFINES = 'TRAP_FPE')

irfLoaderLib = libEnv.StaticLibrary('irfLoader', listFiles(['src/*.cxx']))

progEnv.Tool('irfLoaderLib')
progEnv.Tool('addLibrary', library = progEnv['cppunitLibs'])
test_irfLoaderBin = progEnv.Program('test_irfLoader', listFiles(['src/test/*.cxx']))

progEnv.Tool('registerObjects', package = 'irfLoader', libraries = [irfLoaderLib], testApps = [test_irfLoaderBin], includes = listFiles(['irfLoader/*.h']), pfiles = listFiles(['pfiles/*.par']))
