# -*- python -*-
# $Id$
# Authors: James Chiang <jchiang@slac.stanford.edu>
# Version: irfLoader-01-02-03
Import('baseEnv')
Import('listFiles')
progEnv = baseEnv.Clone()
libEnv = baseEnv.Clone()

if baseEnv['PLATFORM'] == "win32":
    libEnv.Tool('irfLoaderLib', depsOnly = 1)

irfLoaderLib = libEnv.SharedLibrary('irfLoader', listFiles(['src/*.cxx']))

progEnv.Tool('irfLoaderLib')
progEnv.Tool('addLibrary', library = progEnv['cppunitLibs'])
test_irfLoaderBin = progEnv.Program('test_irfLoader', listFiles(['src/test/*.cxx']))

gtirfsBin = progEnv.Program('gtirfs', listFiles(['src/gtirfs/*.cxx']))

progEnv.Tool('registerTargets', package = 'irfLoader',
             libraryCxts = [[irfLoaderLib, libEnv]],
             testAppCxts = [[test_irfLoaderBin, progEnv]],
             includes = listFiles(['irfLoader/*.h']),
             binaryCxts = [[gtirfsBin,progEnv]],
             pfiles = listFiles(['pfiles/*.par']))
